spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moto
    username: bot_usr
    password: zss43rDvI1RuJTdW
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false