package ru.rmatyuk.parsemoto.enums

enum class TypeAdditionalInfo(val text: String) {
    ENGINE("Двигатель"),
    FRONT_PART("Передняя часть"),
    APPEARANCE("Внешний вид"),
    REAR_END("Задняя часть"),
    ELECTRICAL_AND_EXHAUST("Электрика и выхлопная"),
    FRAME("Рама")
}

enum class AdditionalInfo(val text: String) {
    ENGINE("Двигатель"),
    LID("Крышка"),
    OIL_LEAK("Подтёк масла"),
    RADIATOR("Радиатор"),
    CARBURETOR("Карбюратор"),
    CLUTCH("Сцепление"),
    STARTER("Стартер"),
    FORK_EXTERNALLY("Вилка внешне"),
    PLUG_INT("Вилка внутр."),
    TRAVERSE("Траверса"),
    STEERING_WHEEL("Руль"),
    WHEEL("Колесо"),
    BRAKE("Тормоз"),
    TIRE("Шина"),
    ABOVE("Сверху"),
    CENTER("Центр"),
    BOTTOM("Снизу"),
    SIDE("Боковой"),
    TANK("Бак"),
    SEAT("Сиденье"),
    REAR_END("Задняя часть"),
    WING_PER("Крыло пер."),
    REAR_WING("Крыло зад."),
    GLASS("Стекло"),
    SHOCK_ABSORBER("Амортизатор"),
    PENDULUM("Маятник"),
    CHAIN("Цепь"),
    STAR("Звезда"),
    KEY("Ключ"),
    SPEEDOMETER("Спидометр"),
    TURN_SIGNAL("Поворотник"),
    FARAH("Фара"),
    BATTERY("АКБ"),
    SOUND_SIGNAL("Звук сигнал"),
    STOP_SIGNAL("Стоп сигнал"),
    MIRROR("Зеркало"),
    MUFFLER("Глушитель"),
    COLLECTOR("Коллектор"),
    FRAME_OVERALL("Рама общая"),
    FRAME_FROM_BELOW("Рама снизу"),
    LIMITERS("Ограничители"),
    SEAT_RAIL("Рельс сидения"),
    STEP("Подножка"),
    STAND("Подставка")
}
